groq.api.key=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
server.port=8081
spring.activemq.broker-url=tcp://localhost:61616
llm.queue.name=isbn.queue

# Database Configuration
spring.datasource.url=jdbc:sqlite:library.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true